### ISSUE TITLE
Module path should be "github.com/talentlessguy/go-web-app", not "create-go-web-app"

### ISSUE THREAD

**Issue by KateGo520** [talentlessguy/go-web-app#15]
## Background
Module path is inconsistent with go import path.
GO111MODULE=on, run `go get github.com/talentlessguy/go-web-app`:

```
go: downloading github.com/talentlessguy/go-web-app v0.0.0-20200622190614-48b1d7b20b5e
go: github.com/talentlessguy/go-web-app upgrade => v0.0.0-20200622190614-48b1d7b20b5e
go get: github.com/talentlessguy/go-web-app@v0.0.0-20200622190614-48b1d7b20b5e: parsing go.mod:
        module declares its path as: create-go-web-app
                but was required as: github.com/talentlessguy/go-web-app 
```

###  Fix the module path:
1) Rename the module path to "github.com/talentlessguy/go-web-app": https://github.com/mikezss/skl-go/blob/master/go.mod#L1 
```
module github.com/talentlessguy/go-web-app
go 1.12
require (
	…
) 
```
2) Warning the users not to use the module, get "github.com/talentlessguy/go-web-app" in GOPATH mode.

**Comment by KateGo520** [comment]
@talentlessguy @devhammed  Could you help me review this issue? Thx :p

**Comment by talentlessguy** [comment]
@KateGo520 feel free to submit a PR and I'll merge it
